#Name: config.yaml
#Usage: Import from gas_chromatography.py and use values to create GUI.

BODY_FONT_SIZE: 11
HEADER_FONT_SIZE: 18
EXTRA_SPACE: 10
BORDER: 10

DEFAULT_FRAME_SIZE: !!python/tuple [1000,600]
DEFAULT_SASH_SIZE: 350

OVEN_INDEX: 1
INJ_INDEX: 2
SER_DELAY: .01 
